name: s3pl_env
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11.5
  - pip
  - pytorch=2.3.0
  - torchvision=0.18.0
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - tqdm
  - matplotlib
  - scikit-learn
  - scipy
  - h5py
  - pip:
      - m2aia
      - pyimzml
